{{keyword}} targetElement_001 = document.querySelector(`:root > body`);
{{keyword}} html_001 = document.createElement('html');
{{keyword}} text_001 = document.createTextNode(`    `);
html_001.appendChild(text_001);
{{keyword}} head_001 = document.createElement('head');
{{keyword}} text_002 = document.createTextNode(`        `);
head_001.appendChild(text_002);
{{keyword}} meta_001 = document.createElement('meta');
meta_001.setAttribute(`charset`, `utf-8`);
head_001.appendChild(meta_001);
{{keyword}} text_003 = document.createTextNode(`        `);
head_001.appendChild(text_003);
{{keyword}} title_001 = document.createElement('title');
{{keyword}} text_004 = document.createTextNode(`Sample`);
title_001.appendChild(text_004);
head_001.appendChild(title_001);
{{keyword}} text_005 = document.createTextNode(`        `);
head_001.appendChild(text_005);
{{keyword}} link_001 = document.createElement('link');
link_001.setAttribute(`rel`, `stylesheet`);
link_001.setAttribute(`href`, ``);
head_001.appendChild(link_001);
{{keyword}} text_006 = document.createTextNode(`    `);
head_001.appendChild(text_006);
html_001.appendChild(head_001);
{{keyword}} text_007 = document.createTextNode(`    `);
html_001.appendChild(text_007);
{{keyword}} body_001 = document.createElement('body');
{{keyword}} text_008 = document.createTextNode(`        `);
body_001.appendChild(text_008);
{{keyword}} div_001 = document.createElement('div');
div_001.setAttribute(`id`, `container`);
{{keyword}} text_009 = document.createTextNode(`            `);
div_001.appendChild(text_009);
{{keyword}} div_002 = document.createElement('div');
div_002.setAttribute(`id`, `header`);
{{keyword}} text_010 = document.createTextNode(`                `);
div_002.appendChild(text_010);
{{keyword}} comment_001 = document.createComment(` Sample H1 `);
div_002.appendChild(comment_001);
{{keyword}} text_011 = document.createTextNode(`                `);
div_002.appendChild(text_011);
{{keyword}} h1_001 = document.createElement('h1');
{{keyword}} text_012 = document.createTextNode(`Sample`);
h1_001.appendChild(text_012);
div_002.appendChild(h1_001);
{{keyword}} text_013 = document.createTextNode(`                `);
div_002.appendChild(text_013);
{{keyword}} img_001 = document.createElement('img');
img_001.setAttribute(`src`, `kanye.jpg`);
img_001.setAttribute(`alt`, `kanye`);
div_002.appendChild(img_001);
{{keyword}} text_014 = document.createTextNode(`            `);
div_002.appendChild(text_014);
div_001.appendChild(div_002);
{{keyword}} text_015 = document.createTextNode(`            `);
div_001.appendChild(text_015);
{{keyword}} div_003 = document.createElement('div');
div_003.setAttribute(`id`, `main`);
{{keyword}} text_016 = document.createTextNode(`                `);
div_003.appendChild(text_016);
{{keyword}} h2_001 = document.createElement('h2');
{{keyword}} text_017 = document.createTextNode(`Main`);
h2_001.appendChild(text_017);
div_003.appendChild(h2_001);
{{keyword}} text_018 = document.createTextNode(`                `);
div_003.appendChild(text_018);
{{keyword}} p_001 = document.createElement('p');
{{keyword}} text_019 = document.createTextNode(`This is the main content.`);
p_001.appendChild(text_019);
div_003.appendChild(p_001);
{{keyword}} text_020 = document.createTextNode(`                `);
div_003.appendChild(text_020);
{{keyword}} img_002 = document.createElement('img');
img_002.setAttribute(`src`, ``);
img_002.setAttribute(`alt`, ``);
div_003.appendChild(img_002);
{{keyword}} text_021 = document.createTextNode(`            `);
div_003.appendChild(text_021);
div_001.appendChild(div_003);
{{keyword}} text_022 = document.createTextNode(`            `);
div_001.appendChild(text_022);
{{keyword}} div_004 = document.createElement('div');
div_004.setAttribute(`id`, `footer`);
{{keyword}} text_023 = document.createTextNode(`                `);
div_004.appendChild(text_023);
{{keyword}} comment_002 = document.createComment(` Copyright `);
div_004.appendChild(comment_002);
{{keyword}} text_024 = document.createTextNode(`                `);
div_004.appendChild(text_024);
{{keyword}} p_002 = document.createElement('p');
{{keyword}} text_025 = document.createTextNode(`Copyright © 2019`);
p_002.appendChild(text_025);
div_004.appendChild(p_002);
{{keyword}} text_026 = document.createTextNode(`            `);
div_004.appendChild(text_026);
div_001.appendChild(div_004);
{{keyword}} text_027 = document.createTextNode(`        `);
div_001.appendChild(text_027);
body_001.appendChild(div_001);
{{keyword}} text_028 = document.createTextNode(`    `);
body_001.appendChild(text_028);
html_001.appendChild(body_001);
targetElement_001.appendChild(html_001);